version: '3.7'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - kafkanet
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4.1
    container_name: kafka-0
    expose:
      - 9092
    ports:
      - '29092:29092'
    networks:
      - kafkanet
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
networks:
  kafkanet:
    name: kafka-network
volumes:
  kafka_data:
  zookeeper_data:
    driver: local
